
SignPromptReminder = &6在告示牌上写文字，换行即空格！
PromptPlayerOnly = &6CommandPrompter can only be used by a player.!
DelegateInvalidPlayer = &cThe player &6%s&c is not online!
SignPromptMultiArg = &6Sent a multi argument sign prompt. Type the response after the &a&l:
CommandCancelNotInCompletion = &cYou are not in command completion.
CommandReloadSuccess = &a重载成功!
PromptCancel = &c啊哦，您取消了填写内容......
DelegateInvalidArgs = &cInvalid arguments for console delegate command!
PluginVersion = &6Installed Version: &2&l%s
PromptInProgress = &6等一下，你还没填完内容呢！若想取消请回复 &c"%s"&6 。
CompletedCommand = &6Command to execute: &3%s
PCMOutOfBounds = &cThe index &6%s&c is out of bounds!
PromptNoPerm = &cYou don't have permission to use CommandPrompter.
DelegateConsoleOnly = &cThis command can only be executed by the console!
CommandRebuildHeadCacheSuccess = &aSuccessfully rebuilt head cache! (%sms)
DelegateUsage = &6Usage: &3%s