version:
  yml: 38
  mysql: 20230206
  file: 20230206
options:
  check-update: true
  auto-register: false
timer:
  delay: 10
  period: 10
mysql:
  enabled: false
  host: localhost
  port: 3306
  user: root
  password: ''
  database: ''
  maxconns: 16
