# ______  _   _   _____   _   _   ______  _   _   _   _____   _   _       ___   _____  
#|___  / | | | | /  _  \ | | | | |___  / | | | | | | /  ___| | | | |     /   | /  _  \ 
#   / /  | |_| | | | | | | | | |    / /  | |_| | | | | |     | |_| |    / /| | | | | | 
#  / /   |  _  | | | | | | | | |   / /   |  _  | | | | |     |  _  |   / / | | | | | | 
# / /__  | | | | | |_| | | |_| |  / /__  | | | | | | | |___  | | | |  / /  | | | |_| | 
#/_____| |_| |_| \_____/ \_____/ /_____| |_| |_| |_| \_____| |_| |_| /_/   |_| \_____/ 
#
#ZHICHAO出品必属精品


#和风天气官网:  https://dev.qweather.com/


worlds:
  - world

#是否后台报时
printout: false

#是否同步时间时播报给玩家
remind: false

#是否需要时间同步
time-map: false

#是否天气同步,需要注册和风天气账号->创建项目，这个时候有个private key，把private key填到下面

#和风天气提供免费的天气api，精确到每一天的天气
weather-map: true

#是否精确到每小时,如果天气精确到每小时用的是和风天气的标准版，需要一定付费
weather-hour: true

your-key: f46c6add0f0b4230afbbed35fa2e3a25

#天气城市（9位长代码）
city: 101020100


#如果是整时请写 时:00

#日出时间
raise_time: "6:00"

#日落时间
fall_time: "18:30"

sumtime-auto: true
